language: python
python:
  - "3.8"

services:
  - docker

env:
  global:
    - DOCKER_IMAGE=ulrich2002/link_extrator

# Build and push Docker image
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_IMAGE .
  - docker push $DOCKER_IMAGE

# Deploy to Kubernetes
script:
  - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x ./kubectl
  - mkdir -p $HOME/.kube
  - echo "$KUBE_CONFIG" > $HOME/.kube/config
  - ./kubectl apply -f link-spider.yaml

