apiVersion: v1
kind: Pod
metadata:
  name: link-spider
spec:
  containers:
  - name: link-spider-container
    image: ulrich2002/link-spider:latest  
    args: ["-u", "https://news.ycombinator.com", "-u", "https://arstechnica.com", "-o", "json"]
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 1000  # Run as non-root user
  restartPolicy: Never

